language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n snakemake snakemake>=5.1.2 python=$TRAVIS_PYTHON_VERSION
  - conda create -q -n star star
  - source activate star
  # create STAR index (too big to live in git)
  - mkdir .test/data/ref/index
  - STAR --runMode genomeGenerate --genomeDir .test/data/ref/index --genomeFastaFiles .test/data/ref/genome.chr21.fa

script:
  - source activate snakemake
  # run the workflow
  - snakemake --use-conda --directory .test
